spring.application.name=attendance-api
server.port=8080

# External API Configuration
external.api.url=http://117.192.9.195/Attendance_Api/punchReport.php

# Logging
logging.level.root=INFO
logging.level.com.attendance=DEBUG

